### PR TITLE
Update queries.d.ts

### PR DESCRIPTION
**Pull request by wolverineks**
**What**:

Update type of GetByText

**Why**:

Type was incorrect

**How**:

copied type from FindByText / docs

**Checklist**:
- [X] Documentation added to the
      [docs site](https://github.com/bcarroll22/native-testing-library-docs)
- [X] Typescript definitions updated
- [ ] Tests
- [ ] Ready to be merged

### CODE REVIEW

**Comment by wolverineks** [comment]
should a typecheck be added to the ci?

**Comment by wolverineks** [comment]
it also looks like `getByText` uses something called filter, and not selector, which is not in the `MatcherOptions` type

**Comment by wolverineks** [comment]
should there be a text that exercises each of the `MatcherOptions` options?

**Comment by bcarroll22** [comment]
Thanks for this!

I’m open to any improvements to the types or CI pipeline 👍 if you’d like to add more tests to cover extra scenarios, that works for me. The library itself is at 100% test coverage, so all of the matcher options and variations should be covered elsewhere in the tests already, but if you feel like there’s something missing feel free to add it!

**Comment by bcarroll22** [comment]
@wolverineks do we have any updates to this? should we merge or go back to the drawing board? for what it's worth, the rest of the organization either switched or is switching to the types repo, so we may want to just consider doing that here.

**Comment by wolverineks** [comment]
yeah, sorry, i went on vacation and i havent looked at it in a while. 
im fine merging it now, and working on other changes if they become a problem, later
im fine with a types repo, i like the idea of consistency across all the testing-library flavors

**Pull request merged**
