### PR TITLE
feat(navigation): upgrade to latest react-navigation v4

### PR DESCRIPTION
**Pull request by sibelius**
**What**:

I'm upgrading react-navigation test examples to use latest v4 version

**Why**:

This will cause less trouble for newcomers

**How**:

I've upgrade some packages and added related ones

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/bcarroll22/native-testing-library-docs)
- [ ] Typescript definitions updated
- [x] Tests
- [ ] Ready to be merged 

I'm having this error:

```jsx
 /native-testing-library/node_modules/@react-native-community/masked-view/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import MaskedView from './js/MaskedView';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

I've tried to add `@react-native-community/masked-view` on `transformIgnorePatterns` of jest.config.js

but it did not worked

### CODE REVIEW

**Comment by bcarroll22** [comment]
Awesome thanks! @allcontributors please add @sibelius for code.

**Comment by bcarroll22** [comment]
Ah I didn't realize this wasn't ready to be merged, sorry going to revert this 😬 my bad.

**Comment by sibelius** [comment]
If you fix the test, feel free to merge it

**Comment by mvrdrew** [comment]
Hi, I've run into this issue myself today and thought I'd see if I can track down the problem.

@sibelius, from what I can see you were on the right track by adding `@react-native-community` to the `transformIgnorePatterns`, but you added them to the `jest-preset.js` file which doesn't appear to be used by the jest config. If you add that pattern into the `jest.config.js` it works.

I don't know the project well enough to create a PR myself, but hope this helps complete this PR.

**Pull request merged**
