### PR TITLE
Support React Native 0.63.x

### PR DESCRIPTION
**Pull request by daveols**
**What**:

- Support new `Pressable` component
- Remove deprecated `accessibilityStates` and support `accessibilityState.disabled`

Fixed issues: 

#132 - mock `LogBox` in the Jest preset
#126 - remove deprecated native mocks and add some new ones similar to how it's done in React Native core
#113 - fixed by adding the component display name to `TouchableOpacity` and `TouchableHighlight` mocks via Jest preset

I've also upgraded `react-navigation` example tests to reference version v4 and all tests to use the latest React and React Native.

**Why**:

Green tests make me happy.

**How**:

- Refactor mockComponent to take `instanceMethods` and `displayName`
- Add some new mocks to the jest preset
- More testing, fixed some existing tests
- Other stuff; see code

**Checklist**:

- [x] [Documentation added to the docs site](https://github.com/testing-library/native-testing-library-docs/pull/37)
- [x] Typescript definitions updated (N/A)
- [x] Tests
- [x] Ready to be merged 

The documentation will need to be updated to indicate support for `Pressable`.

~This might require a major version bump. I haven't had time to check backwards compatibility outside of React Native 0.62.2.~

*EDIT* 
Confirmed compatibility issues with React Native versions <0.62.0 due to the LogBox mock:

```
 Cannot find module 'react-native/Libraries/LogBox/LogBox' from 'mock-modules.js'
```

Removing the mock makes these changes backwards compatible (at least in the project that I tested it in, 100+ tests, RN@0.61.4). Unless there's a better way to handle LogBox or to somehow conditionally mock it with Jest, we should bump the major version with these changes.

### CODE REVIEW

**Review by vanGalilea — APPROVED** [review]

**Comment by vanGalilea** [comment]
Good work, all fixes we've been waiting for

**Comment by drews256** [comment]
@bcarroll22 what needs to be done to move this forward? Anything I can help push along @daveols or @bcarroll22?

**Comment by daveols** [comment]
@drews256 I don't have any write access. We'll need @bcarroll22 to approve, merge, and cut a new release. In the meantime you can reference my fork in your dependencies in which I have compiled the distribution:

```
"@testing-library/react-native": "github:daveols/native-testing-library#support-react-native-63-dist"
```

I can't guarantee this will be up forever so make sure you update to the latest release once it's out.

**Comment by drews256** [comment]
Yeah, I understand, this comment was mostly pinging @bcarrol22 but figured
I'd ask if you wanted a hand with anything else before he took a look.

**Comment by daveols** [comment]
Ah, gotcha. Nothing from this end @drews256, I think it's good to go.

**Comment by julien9999** [comment]
please merge

**Comment by daveols** [comment]
Apparently this repo is to be deprecated, see: https://github.com/callstack/react-native-testing-library/issues/442

@kentcdodds @nickmccurdy in the meantime it would be great to get these fixes out for those who are still dependent on this project and aren't currently in a position to migrate.

**Comment by daveols** [comment]
Apparently this repo is to be deprecated, see: callstack/react-native-testing-library#442

@kentcdodds @nickmccurdy in the meantime it would be great to get these fixes out for those who are still dependent on this project and aren't currently in a position to migrate.

**Comment by drews256** [comment]
Ahhhh. :-1: Can we confirm @kentcdodds and @nickmccurdy and then please throw a big fat deprecated note on the readme if that is actually the case.

React Native is already hard enough to keep up to date.

**Comment by kentcdodds** [comment]
@all-contributors please add @daveols for code, tests, and docs

**Comment by nickmccurdy** [comment]
@drews256 **Tip:** If you use `Fix #n` or `Fixes #n` in a commit (replacing `n` with an issue number in this repository), it will be closed when merged and the bot will automatically mention the release that fixes it.

**Pull request merged**
