### PR TITLE
Remove dependencies on Haste modules

### PR DESCRIPTION
**Pull request by jeffreyffs**
**What**:

Removes dependencies on haste modules

**Why**:

react-native 0.61.0 RC has been released and Haste modules no longer exist. Trying to find a module by its old Haste name (ie: 'View') no longer works.

**How**:

Changed from Haste module name -> path

**Checklist**:

- [ ] Documentation added to the (N/A)
      [docs site](https://github.com/bcarroll22/native-testing-library-docs)
- [ ] Typescript definitions updated (N/A)
- [x] Tests
- [ ] Ready to be merged 

I tested this against the current version of react-native in the package (0.59.6) and then I upgraded to react-native 0.61 and react 16.9.0 and all the tests also passed.

Also, I'm curious if anyone has a better way to do these mocks. Not in love with all the absolute paths in here.

Would love to get some additional 👀 and testing on this :)

### CODE REVIEW

**Comment by jeffreyffs** [comment]
@bcarroll22 Any thoughts on this approach? I tested this on both 0.59.6 and 0.61.0 RC, so it appears to be backwards compatible.

**Comment by bcarroll22** [comment]
Sorry for the delay, we can merge this to fix the issues for those on later versions if you've tested it on both. The checks still pass, so we're good to go. This doesn't seem like a breaking change, so we'll call it a bugfix, since it fixes compatibility with RN>0.60.0

**Comment by bcarroll22** [comment]
@allcontributors please add @jeffreyffs for code

**Pull request merged**
